version: "3"

services:


        dbph:
                build: ./mysql
                container_name: dbph
                ports:
                        - "3306:3306"

          
               

               



