version: "3"

services:

        webph:
                build: ./gin
                container_name: webph
                ports:
                        - "8888:8888"

        sockph:
                build: ./sio
                container_name: sockph
                ports:
                        - "8889:8889"

        dbph:
                build: ./mysql
                container_name: dbph
                ports:
                        - "3306:3306"

          
               
        trafficph:
                build: ./nginx
                container_name: trafficph
                ports:
                        - "5006:5006"


               



